version: "3.7"

services:
    mysql:
        image: mysql
        env_file: .env
        volumes:
        - ${PWD}/data.sql:/docker-entrypoint-initdb.d/data.sql
        - data:/var/lib/mysql

    app:
        build:
            context: .
            target: prod
        command: ["./wait-for-it.sh", "mysql:3306", "--", "./app"]
        env_file: .env
        depends_on:
        - mysql

volumes:
    data:
